version: '2'

services:
    icmpreceiver:
        image: ispm/icmpreceiver
        environment:
            - CONSUMER_TASKS=10
            - ZBX_SERVER=http://192.168.8.23
            - ZBX_USERNAME=Admin
            - ZBX_PASSWORD=zabbix
            - ZBX_BGAN_TEMPLATE=ISPM - BGAN
            - ZBX_BGAN_HOSTGROUP=BGAN
            - ZBX_BGAN_ITEM=Agent ping
            - ZBX_BGAN_KEY=agent.ping
        tty: true
        volumes:
            - /home/vguedes/projects/keepupz/icmpreceiver:/code
