version: '2'

services:
    keepupz:
        image: ispm/keepupz
        environment:
            - CONSUMER_TASKS=5
            - ZBX_SERVER=192.168.8.23
            - ZBX_USERNAME=Admin
            - ZBX_PASSWORD=zabbix
            - ZBX_TEMPLATE=ISPM - BGAN
            - ZBX_HOSTGROUP=BGAN
            # Comma separated CIDRs
            - ZBX_ALLOWED_NETWORKS=192.168.8.35/32,192.168.8.27/32
            - ZBX_SENDER_KEY=agent.ping
            - ZBX_SERVER_TIMEOUT=120
        tty: true
        volumes:
            - /home/vguedes/projects/keepupz:/code
