version: '2'

services:
    icmpreceiver:
        image: ispm/icmpreceiver
        environment:
            - CONSUMER_TASKS=10
            - ZBX_SERVER=http://192.168.8.23
            - ZBX_USERNAME=Admin
            - ZBX_PASSWORD=zabbix
            - ZBX_TEMPLATE=ISPM - BGAN
            - ZBX_HOSTGROUP=BGAN
            - ZBX_NETWORK=192.168.8.35/32
        tty: true
        volumes:
            - /home/vguedes/projects/keepupz/icmpreceiver:/code
