version: '2'

services:
    keepupz:
        image: ispm/keepupz
        environment:
            - CONSUMER_TASKS=5
            - ZBX_SERVER=201.54.32.50:4887
            - ZBX_USERNAME=keepupz
            - ZBX_PASSWORD=ispmbr01
            - ZBX_TEMPLATE=ISPM - BGAN
            - ZBX_HOSTGROUP=BGAN
            # Comma separated CIDRs
            - ZBX_ALLOWED_NETWORKS=192.168.8.35/32,192.168.8.27/32
            - ZBX_SENDER_KEY=agent.ping
            - ZBX_SERVER_TIMEOUT=120
            - ZBX_WAIT_AFTER_CREATE_HOST=3
        tty: true
        volumes:
            - /home/vguedes/projects/keepupz:/code
